name: "Upload SARIF"

# Run workflow each time code is pushed to your repository.
on:
  pull_request_review_comment: 

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Run smartbugs static analysis
      run: |
          git clone https://github.com/smartbugs/smartbugs.git
          cd smartbugs
          python3 -m pip install -r requirements.txt
          rm -r dataset/
          python3 smartBugs.py --tool conkas --file ../ --unique-sarif-output
          tree
