name: "Upload SARIF"

# Run workflow each time code is pushed to your repository.
on:
  push: 

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Smartbugs
      run: |
          git clone --single-branch --branch module-capability https://github.com/smartbugs/smartbugs.git
          python3 -m pip install -r smartbugs/requirements.txt
          rm -r smartbugs/dataset/
    - name: Run smartbugs static analysis
      run: |
          python3 smartbugs/smartBugs.py --tool conkas --file ./ --unique-sarif-output
          sarif_file="$(basename smartbugs/results/*.sarif)"
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: smartbugs/results/$sarif_file
