name: "Upload SARIF"

# Run workflow each time code is pushed to your repository.
on:
  push:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        echo ${{ github.action_path }}
        echo sha: ${{ github.sha }}
        echo token: ${{ github.token }}
