name: "Upload SARIF"

# Run workflow each time code is pushed to your repository.
on:
  push: 

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Run smartbugs static analysis
      run: |
          git clone https://github.com/smartbugs/smartbugs.git
          python3 -m pip install -r smartbugs/requirements.txt
          rm -r smartbugs/dataset/
          python3 smartbugs/smartBugs.py --tool conkas --file ./
          tree
