name: "Upload SARIF"

# Run workflow each time code is pushed to your repository.
on:
  push: 

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Smartbugs
      run: |
          git clone https://github.com/smartbugs/smartbugs.git
          python3 -m pip install -r smartbugs/requirements.txt
          rm -r smartbugs/dataset/
    - name: Run smartbugs static analysis
      run: |
          cd smartbugs
          python3 smartBugs.py --tool conkas --file ../ --import-path ../ --unique-sarif-output
          tree
