name: "Upload SARIF"

# Run workflow each time code is pushed to your repository.
on:
  push:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Python3 Requests
      run: python3 -m pip install requests
    - name: Send Files Python Script
      run: python3 ./.github/workflows/upload.py
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ./.github/workflows/results.sarif
